
substitutions:
  name: esp-rs485
  device_description: "Monitor two BMS-TDT via RS485 UART-TTL internal"
  bms0_name: "bms0"
  bms1_name: "bms1"
  tx_pin_bms0: GPIO17
  rx_pin_bms0: GPIO18
  tx_pin_bms1: GPIO12
  rx_pin_bms1: GPIO13
  

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-bms"
    version: 2.2.0
  friendly_name: bms-rs485
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# ----------------------------
# External Components
# ----------------------------
external_components:
  - source:
      type: local
      path: ./tdt-bms
    components: [ tdt_bms, tdt_modbus ]
    refresh: 0s

  - source:
      type: local
      path: ./jk-bms
    components: [  jk_rs485_bms, jk_rs485_sniffer ]
    refresh: 0s

logger:
  level: DEBUG

api:
  encryption:
    key: "l4JUVdNNwrrhLgSFdZqKSOTf8Z32xYsRh3hYNR1/vTg="

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BMS-RS485"
    password: "12345678"

#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client

captive_portal:         

# ----------------------------
# UART Configuration
# ----------------------------
# Please set the default baudrate of your TDT BMS model here. It's sometimes 19200 baud instead of 9600.
uart:
  - id: uart_bms0
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE
    tx_pin: ${tx_pin_bms0}
    rx_pin: ${rx_pin_bms0}
    rx_buffer_size: 384

  - id: uart_bms1
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE
    tx_pin: ${tx_pin_bms1}
    rx_pin: ${rx_pin_bms1}
    rx_buffer_size: 384


# ----------------------------
# rs485 mobus Configuration
# ----------------------------
tdt_modbus:
  - id: modbus_bms0
    uart_id: uart_bms0
    rx_timeout: 150ms

  - id: modbus_bms1
    uart_id: uart_bms1
    rx_timeout: 150ms

# ----------------------------
# bms Configuration
# ----------------------------

tdt_bms:
  - id: bms0
    address: 0x01
    protocol_version: 0x01
    tdt_modbus_id: modbus_bms0
    update_interval: 3s

  - id: bms1
    address: 0x01
    protocol_version: 0x01
    tdt_modbus_id: modbus_bms1
    update_interval: 3s


sensor:
  # ==========================================
  # SYSTEM STATUS SENSORS
  # ==========================================
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

  - platform: internal_temperature
    name: "${name} CPU Temperature"
    update_interval: 60s
    entity_category: diagnostic

  - platform: uptime
    name: "${name} System Uptime"
    update_interval: 60s
    entity_category: diagnostic

  # ==========================================
  # --- bms0 sensors ---
  # ==========================================
  - platform: tdt_bms
    tdt_bms_id: bms0 
    min_cell_voltage:
      name: "${bms0_name} min cell voltage"
    max_cell_voltage:
      name: "${bms0_name} max cell voltage"
    min_voltage_cell:
      name: "${bms0_name} min voltage cell"
    max_voltage_cell:
      name: "${bms0_name} max voltage cell"
    delta_cell_voltage:
      name: "${bms0_name} delta cell voltage"
    average_cell_voltage:
      name: "${bms0_name} average cell voltage"
    cell_voltage_1:
      name: "${bms0_name} cell voltage 1"
    cell_voltage_2:
      name: "${bms0_name} cell voltage 2"
    cell_voltage_3:
      name: "${bms0_name} cell voltage 3"
    cell_voltage_4:
      name: "${bms0_name} cell voltage 4"
    cell_voltage_5:
      name: "${bms0_name} cell voltage 5"
    cell_voltage_6:
      name: "${bms0_name} cell voltage 6"
    cell_voltage_7:
      name: "${bms0_name} cell voltage 7"
    cell_voltage_8:
      name: "${bms0_name} cell voltage 8"
    cell_voltage_9:
      name: "${bms0_name} cell voltage 9"
    cell_voltage_10:
      name: "${bms0_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms0_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms0_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms0_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms0_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms0_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms0_name} cell voltage 16"
    temperature_1:
      name: "${bms0_name} environment temperature"
    temperature_2:
      name: "${bms0_name} mosfet temperature"
    temperature_3:
      name: "${bms0_name} temperature 1"
    temperature_4:
      name: "${bms0_name} temperature 2"
    temperature_5:
      name: "${bms0_name} temperature 3"
    temperature_6:
      name: "${bms0_name} temperature 4"
    total_voltage:
      name: "${bms0_name} total voltage"
    current:
      name: "${bms0_name} current"
    power:
      name: "${bms0_name} power"
    charging_power:
      name: "${bms0_name} charging power"
    discharging_power:
      name: "${bms0_name} discharging power"
    residual_capacity:
      name: "${bms0_name} residual capacity"
    battery_capacity:
      name: "${bms0_name} battery capacity"
    rated_capacity:
      name: "${bms0_name} rated capacity"
    state_of_charge:
      name: "${bms0_name} state of charge"
    charging_cycles:
      name: "${bms0_name} charging cycles"
    sampling_voltage:
      name: "${bms0_name} sampling voltage"
    port_voltage:
      name: "${bms0_name} port voltage"

  # ==========================================
  # --- bms1 sensors ---
  # ==========================================
  - platform: tdt_bms
    tdt_bms_id: bms1 
    min_cell_voltage:
      name: "${bms1_name} min cell voltage"
    max_cell_voltage:
      name: "${bms1_name} max cell voltage"
    min_voltage_cell:
      name: "${bms1_name} min voltage cell"
    max_voltage_cell:
      name: "${bms1_name} max voltage cell"
    delta_cell_voltage:
      name: "${bms1_name} delta cell voltage"
    average_cell_voltage:
      name: "${bms1_name} average cell voltage"
    cell_voltage_1:
      name: "${bms1_name} cell voltage 1"
    cell_voltage_2:
      name: "${bms1_name} cell voltage 2"
    cell_voltage_3:
      name: "${bms1_name} cell voltage 3"
    cell_voltage_4:
      name: "${bms1_name} cell voltage 4"
    cell_voltage_5:
      name: "${bms1_name} cell voltage 5"
    cell_voltage_6:
      name: "${bms1_name} cell voltage 6"
    cell_voltage_7:
      name: "${bms1_name} cell voltage 7"
    cell_voltage_8:
      name: "${bms1_name} cell voltage 8"
    cell_voltage_9:
      name: "${bms1_name} cell voltage 9"
    cell_voltage_10:
      name: "${bms1_name} cell voltage 10"
    cell_voltage_11:
      name: "${bms1_name} cell voltage 11"
    cell_voltage_12:
      name: "${bms1_name} cell voltage 12"
    cell_voltage_13:
      name: "${bms1_name} cell voltage 13"
    cell_voltage_14:
      name: "${bms1_name} cell voltage 14"
    cell_voltage_15:
      name: "${bms1_name} cell voltage 15"
    cell_voltage_16:
      name: "${bms1_name} cell voltage 16"
    temperature_1:
      name: "${bms1_name} environment temperature"
    temperature_2:
      name: "${bms1_name} mosfet temperature"
    temperature_3:
      name: "${bms1_name} temperature 1"
    temperature_4:
      name: "${bms1_name} temperature 2"
    temperature_5:
      name: "${bms1_name} temperature 3"
    temperature_6:
      name: "${bms1_name} temperature 4"
    total_voltage:
      name: "${bms1_name} total voltage"
    current:
      name: "${bms1_name} current"
    power:
      name: "${bms1_name} power"
    charging_power:
      name: "${bms1_name} charging power"
    discharging_power:
      name: "${bms1_name} discharging power"
    residual_capacity:
      name: "${bms1_name} residual capacity"
    battery_capacity:
      name: "${bms1_name} battery capacity"
    rated_capacity:
      name: "${bms1_name} rated capacity"
    state_of_charge:
      name: "${bms1_name} state of charge"
    charging_cycles:
      name: "${bms1_name} charging cycles"
    sampling_voltage:
      name: "${bms1_name} sampling voltage"
    port_voltage:
      name: "${bms1_name} port voltage"

text_sensor:
  # ==========================================
  # SYSTEM STATUS SENSORS
  # ==========================================
  - platform: wifi_info
    ip_address:
      name: "${name} IP Address"
      entity_category: diagnostic
    ssid:
      name: "${name} WiFi SSID"
      entity_category: diagnostic
    bssid:
      name: "${name} WiFi BSSID"
      entity_category: diagnostic
    mac_address:
      name: "${name} MAC Address"
      entity_category: diagnostic

  