substitutions:
  name: tdt-bms
  device_description: "Monitor a TDT-BMS via UART-TTL"
  external_components_source: github://vinh97/esphome-seplos-tdt-bms@main
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-TDT-bms"
    version: 2.2.0
#  project:
#    name: "syssi.esphome-TDT-bms"
#    version: 1.1.0
  friendly_name: tdt-bms

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
#      arduino

external_components:
 - source: ${external_components_source}
   refresh: 0s   

# Enable logging
logger:
  level: DEBUG 
# Enable Home Assistant API
#api:
#  encryption:
#    key: "KYH6D656AeIdzDfXNahpqTrdDB0+rjH03pEVK1QRz2w="
#ota:
#  password: "ca6ae8ac942ead5d5a3e5da33d858925"

api:
  encryption:
    key: "EXe1iYMtrrA79T4c1CFupHCsBDAATNM19wzlBY1wYQc="
ota:
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

#mqtt:
#  broker: !secret mqtt_host
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  id: mqtt_client

uart:
  id: uart_0
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
  parity: NONE
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  rx_buffer_size: 384


tdt_modbus:
  id: modbus0
  uart_id: uart_0
  rx_timeout: 150ms

tdt_bms:
  - id: bms0
    address: 0x01
    protocol_version: 0x01
    tdt_modbus_id: modbus0
    update_interval: 10s

sensor:
  - platform: tdt_bms
    tdt_bms_id: bms0 
    min_cell_voltage:
      name: "min cell voltage"
    max_cell_voltage:
      name: "max cell voltage"
    min_voltage_cell:
      name: "min voltage cell"
    max_voltage_cell:
      name: "max voltage cell"
    delta_cell_voltage:
      name: "delta cell voltage"
    average_cell_voltage:
      name: "average cell voltage"
    cell_voltage_1:
      name: "cell voltage 1"
    cell_voltage_2:
      name: "cell voltage 2"
    cell_voltage_3:
      name: "cell voltage 3"
    cell_voltage_4:
      name: "cell voltage 4"
    cell_voltage_5:
      name: "cell voltage 5"
    cell_voltage_6:
      name: "cell voltage 6"
    cell_voltage_7:
      name: "cell voltage 7"
    cell_voltage_8:
      name: "cell voltage 8"
    cell_voltage_9:
      name: "cell voltage 9"
    cell_voltage_10:
      name: "cell voltage 10"
    cell_voltage_11:
      name: "cell voltage 11"
    cell_voltage_12:
      name: "cell voltage 12"
    cell_voltage_13:
      name: "cell voltage 13"
    cell_voltage_14:
      name: "cell voltage 14"
#    cell_voltage_15:
#      name: "${name} cell voltage 15"
#    cell_voltage_16:
#      name: "${name} cell voltage 16"
    temperature_1:
      name: "environment temperature"
    temperature_2:
      name: "mosfet temperature"
    temperature_3:
      name: "temperature 1"
    temperature_4:
      name: "temperature 2"
    temperature_5:
      name: "temperature 3"
    temperature_6:
      name: "temperature 4"
    total_voltage:
      name: "total voltage"
    current:
      name: "current"
    power:
      name: "power"
    charging_power:
      name: "charging power"
    discharging_power:
      name: "discharging power"
    residual_capacity:
      name: "residual capacity"
    battery_capacity:
      name: "battery capacity"
    rated_capacity:
      name: "rated capacity"
    state_of_charge:
      name: "state of charge"
    charging_cycles:
      name: "charging cycles"
    sampling_voltage:
      name: "sampling voltage"
    port_voltage:
      name: "port voltage"
    
